### ISSUE TITLE
String Error Creating Issues

### ISSUE THREAD

**Issue by starragop** [starragop/secure-tcp-python-alpha#7]
Issue 6, String Error, is recreating Issue 5 and Issue 3 after being fixed by using  `conn.send(data.encode())`, line 26, receiver.py.

Log:

> 2018-06-21 15:54:43,775 STCP receiver has began on 192.168.0.5:6430
2018-06-21 15:54:45,274 STCP has started.
2018-06-21 15:54:45,274 STCP has started.
2018-06-21 15:54:45,274 data
2018-06-21 15:54:45,274 data
2018-06-21 15:54:45,274 data
2018-06-21 15:54:45,274 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,275 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,276 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,277 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,278 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,279 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,280 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,281 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,282 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,283 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,284 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,285 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,286 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,287 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,288 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,289 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,290 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,291 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,292 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,293 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,294 data
2018-06-21 15:54:45,295 data
2018-06-21 15:54:45,295 data
2018-06-21 15:54:45,295 STCP STOPPED DUE TO ERROR ON main.py, main()
Traceback (most recent call last):
  File "main.py", line 13, in main
    receiver.receive()
  File "D:\SecureNetworks\SecureTCP\receiver.py", line 26, in receive
    conn.send(data.encode())
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2018-06-21 15:54:45,295 STCP STOPPED DUE TO ERROR ON main.py, main()
Traceback (most recent call last):
  File "main.py", line 13, in main
    receiver.receive()
  File "D:\SecureNetworks\SecureTCP\receiver.py", line 26, in receive
    conn.send(data.encode())
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by starragop** [comment]
Issue might be with the client.

**Comment by starragop** [comment]
Issue #4 is the cause.
